baseURL = 'https://gm-404.github.io/'
languageCode = 'en'
title = '我的博客'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.zh-CN]
    languageName = '简体中文'
    weight = 1
    hasCJKLanguage = true
  [languages.zh-TW]
    languageName = '繁體中文'
    weight = 1
    hasCJKLanguage = true
  [languages.ja]
    languageName = '日本語'
    weight = 1
    hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        
        # 核心修正：将 block 和 inline 定义为 delimiters 的子项
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"], ["$", "$"]]
        
  [markup.highlight]
    guessSyntax = true
    noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true